exports.date = '2017-12-22';

exports.tripData = {
    "DepartureQuery": "ARN", 
    "DestinationQuery":"LPA",
    "ResortQuery":"",
    "CountryQuery":"",
    "DepartureDateFrom":"",
    "DepartureDateTo":"",
    "ReturnDepartureDateFrom":"",
    "ReturnDepartureDateTo":"",
    "DurationGroup":"",
    "OutFlightKey":"",
    "HomeFlightKey":"",
    "ResortKey":"",
    "HotelQuery":"",
    "HotelKey":"",
    "BrowseKey":"",
    "NumberOfFlightOffers":"5",
    "SearchAlternativeDepartures":true,
    "SearchAlternativeDestinations":"",
    "SearchAlternativeDurations":"",
    "IgnoreTransportCapacity":"",
    "BrowseBackward":false,
    "TripTypes":"Package",
    "NumberOfAdults":"",
    "NumberOfChildren":"",
    "ChildAges":"",
    "MarketUnitKey":"VS",
    "PriceCalculationCodes":"WA",
    "PreSelectedExtraKeys":"TravelInsurance",
    "TripData":"",
    "SessionData":""
};