import { Translate } from '../tools';


export const Countries = {
    All: Translate({dk: '', fi: '', no: '', se: 'Alla resmål'}),
    Antigua: Translate({dk: '', fi: '', no: '', se: 'Antigua'}),
    Aruba: Translate({dk: '', fi: '', no: '', se: 'Aruba'}),
    Austria: Translate({dk: '', fi: '', no: '', se: 'Österrike'}),
    Barbados: Translate({dk: '', fi: '', no: '', se: 'Barbados'}),
    Belgium: Translate({dk: '', fi: '', no: '', se: 'Belgien'}),
    Brazil: Translate({dk: '', fi: '', no: '', se: 'Brasilien'}),
    Bulgaria: Translate({dk: '', fi: '', no: '', se: 'Bulgarien'}),
    Czech: Translate({dk: '', fi: '', no: '', se: 'Tjeckien'}),
    Curacao: Translate({dk: '', fi: '', no: '', se: 'Curaçao'}),
    Cyprus: Translate({dk: '', fi: '', no: '', se: 'Cypern'}),
    Denmark: Translate({dk: '', fi: '', no: '', se: 'Danmark'}),
    DominicanRepublic: Translate({dk: '', fi: '', no: '', se: 'Dominikanska republiken'}),
    Egypt: Translate({dk: '', fi: '', no: '', se: 'Egypten'}),
    Estonia: Translate({dk: '', fi: '', no: '', se: 'Estland'}),
    France: Translate({dk: '', fi: '', no: '', se: 'Frankrike'}),
    Gambia: Translate({dk: '', fi: '', no: '', se: 'Gambia'}),
    Germany: Translate({dk: '', fi: '', no: '', se: 'Tyskland'}),
    Greece: Translate({dk: '', fi: '', no: '', se: 'Grekland'}),
    GreatBritain: Translate({dk: '', fi: 'Iso-Britannia', no: '', se: 'Storbritannien'}),
    Hungary: Translate({dk: '', fi: '', no: '', se: 'Ungern'}),
    India: Translate({dk: '', fi: '', no: '', se: 'Indien'}),
    Indonesien: Translate({dk: '', fi: '', no: '', se: 'Indonesien'}),
    Ireland: Translate({dk: '', fi: '', no: '', se: 'Irland'}),
    Iceland: Translate({dk: '', fi: '', no: '', se: 'Island'}),
    Italy: Translate({dk: '', fi: '', no: '', se: 'Italien'}),
    Jamaica: Translate({dk: '', fi: '', no: '', se: 'Jamaica'}),
    CapeVerde: Translate({dk: '', fi: '', no: '', se: 'Kap Verde'}),
    Croatia: Translate({dk: '', fi: '', no: '', se: 'Kroatien'}),
    Cuba: Translate({dk: '', fi: '', no: '', se: 'Kuba'}),
    Latvia: Translate({dk: '', fi: '', no: '', se: 'Lettland'}),
    Lithuania: Translate({dk: '', fi: '', no: '', se: 'Litauen'}),
    Malaysia: Translate({dk: '', fi: '', no: '', se: 'Malaysia'}),
    Maldives: Translate({dk: '', fi: '', no: '', se: 'Maldiverna'}),
    Malta: Translate({dk: '', fi: '', no: '', se: 'Malta'}),
    Morocco: Translate({dk: '', fi: '', no: '', se: 'Marocko'}),
    Mauritius: Translate({dk: '', fi: '', no: '', se: 'Mauritius'}),
    Mexico: Translate({dk: '', fi: '', no: '', se: 'Mexiko'}),
    Netherlands: Translate({dk: '', fi: '', no: '', se: 'Nederländerna'}),
    Poland: Translate({dk: '', fi: '', no: '', se: 'Polen'}),
    Portugal: Translate({dk: '', fi: '', no: '', se: 'Portugal'}),
    PuertoRico: Translate({dk: '', fi: '', no: '', se: 'Puerto Rico'}),
    Seychelles: Translate({dk: '', fi: '', no: '', se: 'Seychellerna'}),
    Singapore: Translate({dk: '', fi: '', no: '', se: 'Singapore'}),
    Spain: Translate({dk: '', fi: '', no: '', se: 'Spanien'}),
    SriLanka: Translate({dk: '', fi: '', no: '', se: 'Sri Lanka'}),
    StMartin: Translate({dk: '', fi: '', no: '', se: 'St Martin/St Maarten'}),
    SouthAfrica: Translate({dk: '', fi: '', no: '', se: 'Sydafrika'}),
    Tanzania: Translate({dk: '', fi: '', no: '', se: 'Tanzania'}),
    Thailand: Translate({dk: '', fi: '', no: '', se: 'Thailand'}),
    Turkey: Translate({dk: '', fi: '', no: '', se: 'Turkiet'}),
    USA: Translate({dk: '', fi: '', no: '', se: 'USA'}),
    UnitedArabEmirates: Translate({dk: '', fi: '', no: '', se: 'Förenade Arabemiraten'}),
    Vietnam: Translate({dk: '', fi: '', no: '', se: 'Vietnam'})
};